version: '3.5'

services:
  app:
    image: docker.leo9000.de/lzfw/php-apache2-basic-auth-manager
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    #environment:
      #VIRTUAL_HOST: '${VIRTUAL_HOST:-passwords.halle.tech}'
      #LETSENCRYPT_HOST: '${VIRTUAL_HOST:-passwords.halle.tech}'
      #LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
    ports:
      - 80:80
    volumes:
      - ./config.yml:/var/www/config.yml
      - passwords:/var/htsecrets/

volumes:
  passwords:
    external:
      name: frontend-proxy_passwords

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

