version: '3.5'

services:
  app:
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL
    volumes:
      - ./config.yml:/var/www/config.yml
      - passwords:/var/htsecrets/

volumes:
  passwords:
    external:
      name: frontend-proxy_passwords

networks:
  proxy-network:
    name: global-proxy-network
    external: true

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

